development:
  adapter: postgresql
  encoding: unicode
  database: mancini_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: mancini_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: mancini_production
  pool: 5